import { Shield, AlertTriangle } from 'lucide-react';
import Link from 'next/link';

export const metadata = {
    title: 'Disclaimer — Swiss Shield',
    description: 'Important disclaimers about the Swiss Shield document automation service.',
};

export default function DisclaimerPage() {
    return (
        <div className="min-h-screen bg-slate-50">
            <header className="bg-slate-900 py-6">
                <div className="max-w-4xl mx-auto px-4">
                    <Link href="/" className="flex items-center gap-2 text-white">
                        <Shield className="w-6 h-6 text-red-500" />
                        <span className="font-semibold">Swiss Shield</span>
                    </Link>
                </div>
            </header>

            <main className="max-w-4xl mx-auto px-4 py-12">
                <h1 className="text-3xl font-bold text-gray-900 mb-8">Disclaimer</h1>

                <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
                    <div className="flex items-start gap-3">
                        <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0" />
                        <div>
                            <h2 className="font-semibold text-amber-800 text-lg">Important Notice</h2>
                            <p className="text-amber-700 mt-2">
                                Swiss Shield is a <strong>document automation service</strong>, not a law firm.
                                We do not provide legal, tax, or financial advice.
                            </p>
                        </div>
                    </div>
                </div>

                <div className="prose prose-slate max-w-none">
                    <h2>1. Not Legal Advice</h2>
                    <p>
                        The documents generated by Swiss Shield are based on publicly available templates and
                        information. They are provided "as is" without any warranty of legal validity or
                        acceptance by any church authority.
                    </p>
                    <p>
                        If you have complex circumstances (e.g., ongoing disputes with a church, questions
                        about retroactive tax implications, or multi-canton situations), we recommend
                        consulting a qualified legal professional or tax advisor.
                    </p>

                    <h2>2. No Guarantee of Outcome</h2>
                    <p>
                        We cannot guarantee that:
                    </p>
                    <ul>
                        <li>Your church resignation will be accepted</li>
                        <li>Your church tax will be refunded retroactively</li>
                        <li>The address we provide is 100% current (parishes may change boundaries)</li>
                        <li>Processing times will meet any specific deadline</li>
                    </ul>

                    <h2>3. Your Responsibility</h2>
                    <p>
                        You are solely responsible for:
                    </p>
                    <ul>
                        <li>Verifying that you are a registered member of the stated confession</li>
                        <li>Providing accurate personal information</li>
                        <li>Printing, signing, and mailing the letter correctly</li>
                        <li>Following up with the church office if needed</li>
                    </ul>

                    <h2>4. Variations by Canton</h2>
                    <p>
                        Church tax and resignation procedures vary significantly by canton. Some cantons
                        (e.g., Geneva, Vaud, Neuchâtel) have different rules than German-speaking cantons.
                        We attempt to route your letter correctly, but local requirements may vary.
                    </p>

                    <h2>5. No Relationship Created</h2>
                    <p>
                        Using Swiss Shield does not create an attorney-client, accountant-client, or any
                        other professional service relationship.
                    </p>

                    <h2>Contact Us</h2>
                    <p>
                        If you have questions about a specific situation, please consult a professional.
                        For questions about our service, email <a href="mailto:support@swissshield.ch">support@swissshield.ch</a>
                    </p>
                </div>
            </main>

            <footer className="border-t border-gray-200 py-8 mt-12">
                <div className="max-w-4xl mx-auto px-4 text-center text-gray-500 text-sm">
                    © 2026 Swiss Shield. Document automation service. Not legal advice.
                </div>
            </footer>
        </div>
    );
}
